### ISSUE TITLE
[ERROR] 'dependencies.dependency.version' for com.alipay.sofa:runtime-sofa-boot-starter:jar:ark-plugin is missing. @ line 26, column 21

### ISSUE THREAD

**Issue by wangkz** [alipay/sofa-jarslink#101]
app-one maven编译出错
[ERROR] 'dependencies.dependency.version' for com.alipay.sofa:runtime-sofa-boot-starter:jar:ark-plugin is missing. @ line 26, column 21

**Comment by QilongZhang** [comment]
刚改了示例工程 , 麻烦重新拉下代码

**Comment by wangkz** [comment]
**biz-jvm-invocation-sample** 工程maven编译成功，在运行其中的app-one工程后出错，麻烦看一下，以下是全部运行日志
C:\Users\kkkk\Desktop>java -jar app-one-1.0.0-executable-ark.jar
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.sofa.ark Log4j ]
log4j:WARN No appenders could be found for logger (com.alipay.sofa.common.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.sofa.jarslink Log4j ]
log4j:WARN No appenders could be found for logger (com.alipay.sofa.common.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

 ,---.    ,-----.  ,------.   ,---.     ,-----.                     ,--.
'   .-'  '  .-.  ' |  .---'  /  O  \    |  |) /_   ,---.   ,---.  ,-'  '-.
`.  `-.  |  | |  | |  `--,  |  .-.  |   |  .-.  \ | .-. | | .-. | '-.  .-'
.-'    | '  '-'  ' |  |`    |  | |  |   |  '--' / ' '-' ' ' '-' '   |  |
`-----'   `-----'  `--'     `--' `--'   `------'   `---'   `---'    `--'


Spring Boot Version: 1.5.16.RELEASE (v1.5.16.RELEASE)
SOFABoot Version: 2.5.0 (v2.5.0)
Powered By Ant Financial Services Group

Sofa-Middleware-Log SLF4J : Actual logging.path is [ ./logs ]
2018-10-24 15:08:09.959  INFO 33512 --- [           main] com.alipay.sofa.common.log               : Sofa-Middleware-Log SLF4J : Actual logging.path is [ ./logs ]
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.sofa.infra Logback ]
2018-10-24 15:08:09.997  INFO 33512 --- [           main] com.alipay.sofa.common.log               : Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.sofa.infra Logback ]
Sofa-Middleware-Log SLF4J : Actual logging.path is [ ./logs ]
2018-10-24 15:08:10.212  INFO 33512 --- [           main] com.alipay.sofa.common.log               : Sofa-Middleware-Log SLF4J : Actual logging.path is [ ./logs ]
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.sofa.runtime Logback ]
Sofa-Middleware-Log SLF4J Error : Build ILoggerFactory error! Default app logger will be used., java.lang.LinkageError: loader constraint violation: loader (instance of com/alipay/sofa/ark/container/service/classloader/PluginClassLoader) previously initiated loading for a different type with name "org/slf4j/Logger"
java.lang.LinkageError: loader constraint violation: loader (instance of com/alipay/sofa/ark/container/service/classloader/PluginClassLoader) previously initiated loading for a different type with name "org/slf4j/Logger"
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassloader.resolveLocalClass(AbstractClasspathClassloader.java:245)
        at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.loadClassInternal(PluginClassLoader.java:79)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassloader.loadClass(AbstractClasspathClassloader.java:66)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.slf4j.LoggerFactory.<clinit>(LoggerFactory.java:86)
        at com.alipay.sofa.common.log.Constants.<clinit>(Constants.java:31)
        at com.alipay.sofa.common.utils.ReportUtil.report(ReportUtil.java:32)
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.createILoggerFactory(MultiAppLoggerSpaceManager.java:291)
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.getILoggerFactoryBySpaceName(MultiAppLoggerSpaceManager.java:220)
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.getLoggerBySpace(MultiAppLoggerSpaceManager.java:171)
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.getLoggerBySpace(MultiAppLoggerSpaceManager.java:115)
        at com.alipay.sofa.common.log.LoggerSpaceManager.getLoggerBySpace(LoggerSpaceManager.java:57)
        at com.alipay.sofa.common.log.LoggerSpaceManager.getLoggerBySpace(LoggerSpaceManager.java:42)
        at com.alipay.sofa.runtime.spi.log.SofaRuntimeLoggerFactory.getLogger(SofaRuntimeLoggerFactory.java:41)
        at com.alipay.sofa.runtime.spi.log.SofaRuntimeLoggerFactory.getLogger(SofaRuntimeLoggerFactory.java:53)
        at com.alipay.sofa.runtime.spring.initializer.SofaRuntimeSpringContextInitializer.initialize(SofaRuntimeSpringContextInitializer.java:44)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:301)
        at me.qlong.AppOneApplication.main(AppOneApplication.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
        at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:179)
        at com.alipay.sofa.jarslink.integration.deployer.JarslinkDeployer.deploy(JarslinkDeployer.java:60)
        at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.deploy(BizDeployServiceImpl.java:55)
        at com.alipay.sofa.ark.container.pipeline.DeployBizStage.process(DeployBizStage.java:44)
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:73)
        at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:113)
        at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:108)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:52)
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35)
2018-10-24 15:08:10.589 ERROR 33512 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.NoClassDefFoundError: Could not initialize class com.alipay.sofa.common.log.Constants
        at com.alipay.sofa.common.utils.ReportUtil.reportError(ReportUtil.java:45) ~[sofa-common-tools-1.0.14.jar!/:na]
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.createILoggerFactory(MultiAppLoggerSpaceManager.java:359) ~[sofa-common-tools-1.0.14.jar!/:na]
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.getILoggerFactoryBySpaceName(MultiAppLoggerSpaceManager.java:220) ~[sofa-common-tools-1.0.14.jar!/:na]
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.getLoggerBySpace(MultiAppLoggerSpaceManager.java:171) ~[sofa-common-tools-1.0.14.jar!/:na]
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.getLoggerBySpace(MultiAppLoggerSpaceManager.java:115) ~[sofa-common-tools-1.0.14.jar!/:na]
        at com.alipay.sofa.common.log.LoggerSpaceManager.getLoggerBySpace(LoggerSpaceManager.java:57) ~[sofa-common-tools-1.0.14.jar!/:na]
        at com.alipay.sofa.common.log.LoggerSpaceManager.getLoggerBySpace(LoggerSpaceManager.java:42) ~[sofa-common-tools-1.0.14.jar!/:na]
        at com.alipay.sofa.runtime.spi.log.SofaRuntimeLoggerFactory.getLogger(SofaRuntimeLoggerFactory.java:41) ~[runtime-sofa-boot-starter-2.5.0.jar!/:2.5.0]
        at com.alipay.sofa.runtime.spi.log.SofaRuntimeLoggerFactory.getLogger(SofaRuntimeLoggerFactory.java:53) ~[runtime-sofa-boot-starter-2.5.0.jar!/:2.5.0]
        at com.alipay.sofa.runtime.spring.initializer.SofaRuntimeSpringContextInitializer.initialize(SofaRuntimeSpringContextInitializer.java:44) ~[runtime-sofa-boot-starter-2.5.0.jar!/:2.5.0]
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567) ~[spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338) ~[spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:301) ~[spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
        at me.qlong.AppOneApplication.main(AppOneApplication.java:29) [app-one-1.0.0-ark-biz.jar!/:1.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48) [sofa-ark-archive-0.5.2.jar!/:na]
        at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:179) [sofa-ark-container-0.5.2.jar!/:na]
        at com.alipay.sofa.jarslink.integration.deployer.JarslinkDeployer.deploy(JarslinkDeployer.java:60) [sofa-jarslink-ark-starter-2.0.0-SNAPSHOT.jar!/:na]
        at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.deploy(BizDeployServiceImpl.java:55) [sofa-ark-container-0.5.2.jar!/:na]
        at com.alipay.sofa.ark.container.pipeline.DeployBizStage.process(DeployBizStage.java:44) [sofa-ark-container-0.5.2.jar!/:na]
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:73) [sofa-ark-container-0.5.2.jar!/:na]
        at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:113) [sofa-ark-container-0.5.2.jar!/:na]
        at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:69) [sofa-ark-container-0.5.2.jar!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48) [sofa-ark-archive-0.5.2.jar!/:na]
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:108) [app-one-1.0.0-executable-ark.jar:1.0.0]
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:52) [app-one-1.0.0-executable-ark.jar:1.0.0]
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35) [app-one-1.0.0-executable-ark.jar:1.0.0]

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:108)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:52)
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35)
Caused by: com.alipay.sofa.ark.exception.ArkException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:79)
        at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:113)
        at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:69)
        ... 8 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.alipay.sofa.jarslink.integration.deployer.JarslinkDeployer.deploy(JarslinkDeployer.java:64)
        at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.deploy(BizDeployServiceImpl.java:55)
        at com.alipay.sofa.ark.container.pipeline.DeployBizStage.process(DeployBizStage.java:44)
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:73)
        ... 10 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
        at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:179)
        at com.alipay.sofa.jarslink.integration.deployer.JarslinkDeployer.deploy(JarslinkDeployer.java:60)
        ... 13 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.alipay.sofa.common.log.Constants
        at com.alipay.sofa.common.utils.ReportUtil.reportError(ReportUtil.java:45)
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.createILoggerFactory(MultiAppLoggerSpaceManager.java:359)
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.getILoggerFactoryBySpaceName(MultiAppLoggerSpaceManager.java:220)
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.getLoggerBySpace(MultiAppLoggerSpaceManager.java:171)
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.getLoggerBySpace(MultiAppLoggerSpaceManager.java:115)
        at com.alipay.sofa.common.log.LoggerSpaceManager.getLoggerBySpace(LoggerSpaceManager.java:57)
        at com.alipay.sofa.common.log.LoggerSpaceManager.getLoggerBySpace(LoggerSpaceManager.java:42)
        at com.alipay.sofa.runtime.spi.log.SofaRuntimeLoggerFactory.getLogger(SofaRuntimeLoggerFactory.java:41)
        at com.alipay.sofa.runtime.spi.log.SofaRuntimeLoggerFactory.getLogger(SofaRuntimeLoggerFactory.java:53)
        at com.alipay.sofa.runtime.spring.initializer.SofaRuntimeSpringContextInitializer.initialize(SofaRuntimeSpringContextInitializer.java:44)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:301)
        at me.qlong.AppOneApplication.main(AppOneApplication.java:29)
        ... 20 more

**Comment by puzhi** [comment]
@QilongZhang 不知道demo改好啦吗？拉取下拉依然报这个错误呢！！！

**Comment by QilongZhang** [comment]
@wangkz  抱歉，忘了回复。这个问题已经在 https://github.com/alipay/sofa-jarslink/issues/104 修复，我这边修改下文档，你可以重新测试。

**Comment by wangkz** [comment]
@QilongZhang 已经修复了，感谢~
