### ISSUE TITLE
使用sofaboot 3.0 和 jarslink2.0 进行项目动态部署时报异常， 属于启动异常

### ISSUE THREAD

**Issue by iteaj** [alipay/sofa-jarslink#103]
### Describe the bug
使用jarslink动态管理多个应用， 采用的是合并部署里面动态打包部署， 要求是能在多个应用之间进行jvm服务通信

以下是报出的异常：
java.lang.LinkageError: loader constraint violation: loader (instance of com/alipay/sofa/ark/container/service/classloader/PluginClassLoader) previously initiated loading for a different type with name "org/slf4j/Logger"
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassloader.resolveLocalClass(AbstractClasspathClassloader.java:245)
        at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.loadClassInternal(PluginClassLoader.java:79)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassloader.loadClass(AbstractClasspathClassloader.java:66)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.slf4j.LoggerFactory.<clinit>(LoggerFactory.java:86)
        at com.alipay.sofa.common.log.Constants.<clinit>(Constants.java:31)
        at com.alipay.sofa.common.utils.ReportUtil.reportWarn(ReportUtil.java:37)
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.createILoggerFactory(MultiAppLoggerSpaceManager.java:274)
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.getILoggerFactoryBySpaceName(MultiAppLoggerSpaceManager.java:220)
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.getLoggerBySpace(MultiAppLoggerSpaceManager.java:171)
        at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.getLoggerBySpace(MultiAppLoggerSpaceManager.java:115)
        at com.alipay.sofa.common.log.LoggerSpaceManager.getLoggerBySpace(LoggerSpaceManager.java:57)
        at com.alipay.sofa.common.log.LoggerSpaceManager.getLoggerBySpace(LoggerSpaceManager.java:42)
        at com.alipay.sofa.runtime.spi.log.SofaRuntimeLoggerFactory.getLogger(SofaRuntimeLoggerFactory.java:41)
        at com.alipay.sofa.runtime.spi.log.SofaRuntimeLoggerFactory.getLogger(SofaRuntimeLoggerFactory.java:53)
        at com.alipay.sofa.runtime.spring.initializer.SofaRuntimeSpringContextInitializer.initialize(SofaRuntimeSpringContextInitializer.java:44)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:633)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
        at com.iteaj.ark.ArkApplication.main(ArkApplication.java:14)

### Expected behavior
以下是maven：
<dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-jarslink-ark-starter</artifactId>
            <classifier>ark-plugin</classifier>
            <version>2.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <version>3.0.0-SNAPSHOT</version>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>runtime-sofa-boot-starter</artifactId>
        </dependency>
        <dependency>
            <version>3.0.0-SNAPSHOT</version>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>runtime-sofa-boot-plugin</artifactId>
        </dependency>
### Environment

- Jarslink version: 2.0
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): windows10
- Maven version:3.3.9
- IDE version: idea

**Comment by iteaj** [comment]
这个是demo
[demo.zip](https://github.com/alipay/sofa-jarslink/files/2545993/demo.zip)

**Comment by QilongZhang** [comment]
@iteaj  感谢反馈，确认是我们代码问题。已经修复，麻烦将本地  runtime-sofa-boot-plugin 3.0.0-SNAPSHOT  包删除，拉取最新的修复包

**Comment by iteaj** [comment]
我刚才拉取试了以下，  启动还是报错，  这个问题是什么原因导致的，  找了很久，都没找出问题的原因
![0 f27tpf8wazgw 3s0z yf](
![8au8 1o c likf8 bhb9](https://user-images.githubusercontent.com/20572358/47980287-f10a4880-e101-11e8-8a2e-474e921d302a.png)
https://user-images.githubusercontent.com/20572358/47980251-c4563100-e101-11e8-9ad8-b0cbd44c3333.png)
题

**Comment by QilongZhang** [comment]
@iteaj  你清空了本地缓存吗？ 修复之后的包应该是不会报错的。

**Comment by QilongZhang** [comment]
修复 PR  在 https://github.com/alipay/sofa-boot/pull/259 .

**Comment by iteaj** [comment]
好的，  刚才重新拉了以下，已经可以
